// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: id_generator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateIdRequest) Reset() {
	*x = GenerateIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_id_generator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIdRequest) ProtoMessage() {}

func (x *GenerateIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_id_generator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIdRequest.ProtoReflect.Descriptor instead.
func (*GenerateIdRequest) Descriptor() ([]byte, []int) {
	return file_id_generator_proto_rawDescGZIP(), []int{0}
}

type GenerateIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GenerateIdResponse) Reset() {
	*x = GenerateIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_id_generator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIdResponse) ProtoMessage() {}

func (x *GenerateIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_id_generator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIdResponse.ProtoReflect.Descriptor instead.
func (*GenerateIdResponse) Descriptor() ([]byte, []int) {
	return file_id_generator_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateIdResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_id_generator_proto protoreflect.FileDescriptor

var file_id_generator_proto_rawDesc = []byte{
	0x0a, 0x12, 0x69, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x13, 0x0a, 0x11, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x32, 0x52, 0x0a, 0x0b, 0x49, 0x64, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x43, 0x0a, 0x0a, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x49, 0x64, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_id_generator_proto_rawDescOnce sync.Once
	file_id_generator_proto_rawDescData = file_id_generator_proto_rawDesc
)

func file_id_generator_proto_rawDescGZIP() []byte {
	file_id_generator_proto_rawDescOnce.Do(func() {
		file_id_generator_proto_rawDescData = protoimpl.X.CompressGZIP(file_id_generator_proto_rawDescData)
	})
	return file_id_generator_proto_rawDescData
}

var file_id_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_id_generator_proto_goTypes = []any{
	(*GenerateIdRequest)(nil),  // 0: proto.GenerateIdRequest
	(*GenerateIdResponse)(nil), // 1: proto.GenerateIdResponse
}
var file_id_generator_proto_depIdxs = []int32{
	0, // 0: proto.IdGenerator.GenerateId:input_type -> proto.GenerateIdRequest
	1, // 1: proto.IdGenerator.GenerateId:output_type -> proto.GenerateIdResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_id_generator_proto_init() }
func file_id_generator_proto_init() {
	if File_id_generator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_id_generator_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GenerateIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_id_generator_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GenerateIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_id_generator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_id_generator_proto_goTypes,
		DependencyIndexes: file_id_generator_proto_depIdxs,
		MessageInfos:      file_id_generator_proto_msgTypes,
	}.Build()
	File_id_generator_proto = out.File
	file_id_generator_proto_rawDesc = nil
	file_id_generator_proto_goTypes = nil
	file_id_generator_proto_depIdxs = nil
}
