name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  
jobs:

  create-envfile:

    runs-on: ubuntu-22.04

    steps:

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_DEBUG: false
        envkey_DATACENTER_ID: 1
        envkey_WORKER_ID: 0
        file_name: .env

  build:

    runs-on: ubuntu-22.04

    steps:

    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Setup Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.5' # The Go version to download (if necessary) and use.

    - name: Installing protoc-gen-go
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.2
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
        export PATH="$PATH:$(go env GOPATH)/bin"

    - name: Build the Docker image
      run: make build_prod
